twig:
    file_name_pattern: "*.twig"
    form_themes:
        - "form/fields.html.twig"
    globals:
        site_name: "%site_name%"
        main_color: "%main_color%"
        project_name: "%project_name%"
        project_url: "%project_url%"
        project_url_display: "%project_url_display%"
        helloasso_registration_campaign_url: "%helloasso_registration_campaign_url%"
        due_duration_by_cycle: "%due_duration_by_cycle%"
        registration_duration: "%registration_duration%"
        support_email: "%transactional_mailer_user%"
        images_tmp_dir: "%images_tmp_dir%"
        maximum_nb_of_beneficiaries_in_membership: "%maximum_nb_of_beneficiaries_in_membership%"
        allow_extra_shifts: "%allow_extra_shifts%"
        time_after_which_members_are_late_with_shifts: "%time_after_which_members_are_late_with_shifts%"
        max_time_in_advance_to_book_extra_shifts: "%max_time_in_advance_to_book_extra_shifts%"
        code_generation_enabled: "%code_generation_enabled%"
        local_currency_name: "%local_currency_name%"
        use_fly_and_fixed: "%use_fly_and_fixed%"
        max_event_proxy_per_member: "%max_event_proxy_per_member%"
        use_time_log_saving: "%use_time_log_saving%"
        display_gauge: "%display_gauge%"
        max_nb_of_past_cycles_to_display: "%max_nb_of_past_cycles_to_display%"
        profile_display_task_list: "%profile_display_task_list%"
        profile_display_time_log: "%profile_display_time_log%"
        # user
        user_account_not_enabled_material_icon: "%user_account_not_enabled_material_icon%"
        user_account_enabled_material_icon: "%user_account_enabled_material_icon%"
        # member
        member_withdrawn_icon: "%member_withdrawn_icon%"
        member_withdrawn_material_icon: "%member_withdrawn_material_icon%"
        member_withdrawn_background_color: "%member_withdrawn_background_color%"
        member_frozen_icon: "%member_frozen_icon%"
        member_frozen_material_icon: "%member_frozen_material_icon%"
        member_frozen_background_color: "%member_frozen_background_color%"
        member_exempted_icon: "%member_exempted_icon%"
        member_exempted_material_icon: "%member_exempted_material_icon%"
        member_exempted_background_color: "%member_exempted_background_color%"
        member_registration_missing_icon: "%member_registration_missing_icon%"
        member_registration_missing_material_icon: "%member_registration_missing_material_icon%"
        member_registration_missing_background_color: "%member_registration_missing_background_color%"
        # beneficiary
        beneficiary_main_icon: "%beneficiary_main_icon%"
        beneficiary_new_icon: "%beneficiary_new_icon%"
        beneficiary_flying_icon: "%beneficiary_flying_icon%"
        # swipe card
        display_swipe_cards_settings: "%display_swipe_cards_settings%"
        display_freeze_account: "%display_freeze_account%"
        display_freeze_account_false_message: "%display_freeze_account_false_message%"
        display_keys_shop: "%display_keys_shop%"
        display_name_shifters: "%display_name_shifters%"
        use_card_reader_to_validate_shifts: "%use_card_reader_to_validate_shifts%"
        # fly and fixed
        fly_and_fixed_allow_fixed_shift_free: "%fly_and_fixed_allow_fixed_shift_free%"
        # time log saving
        time_log_saving_shift_free_min_time_in_advance_days: "%time_log_saving_shift_free_min_time_in_advance_days%"
        # services
        beneficiary_service: "@App\\Service\\BeneficiaryService"
        membership_service: "@App\\Service\\MembershipService"
        shift_service: "@App\\Service\\ShiftService"
        time_log_service: "@App\\Service\\TimeLogService"

when@test:
    twig:
        strict_variables: true
