services:
  php:
    build:
      context: .
      target: frankenphp_dev
    environment:
      SERVER_NAME: :80
      APP_SECRET: ${APP_SECRET:-!ChangeMe!}
      DATABASE_URL: mysql://app:gestioncompte@database:3306/app?serverVersion=10.11.2-MariaDB&charset=utf8mb4
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
    volumes:
      - .:/app
      - /app/var
    ports:
      - "8001:80"
      # - "443:443"
      # - "443:443/udp"
    tty: true

  database:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: gestioncompte
      MARIADB_DATABASE: app
      MARIADB_USER: app
      MARIADB_PASSWORD: gestioncompte
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
