# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    time_after_which_members_are_late_with_shifts: -9
    registration_period: "15 days ago"
    remainder_warning_delay: "15"
    images_tmp_dir: "%kernel.project_dir%/public/tmp"
    registration_every_civil_year: false
    use_fly_and_fixed: false
    swipe_card_logging: true
    swipe_card_logging_anonymous: true
    use_time_log_saving: false
    time_log_saving_shift_free_min_time_in_advance_days: 0
    registration_duration: "1 year"
    cycle_type: abcd
    user_account_enabled_icon: ☑
    member_withdrawn_icon: ∅
    enable_place_local_ip_address_check: true
    place_local_ip_address: "127.0.0.1,192.168.0.x"
    member_frozen_icon: ❄️
    member_exempted_icon: ☂
    member_registration_missing_icon: $
    beneficiary_flying_icon: ✈
    emails.base_domain: yourcoop.local
    project_name: "My Local Coop"
    site_name: "Espace membre @ MyLocalCoop"
    project_url: "https://yourcoop.local/"
    project_url_display: "yourcoop.local"
    main_color: "#51CAE9"
    local_currency_name: "monnaie locale"
    code_generation_enabled: true
    due_duration_by_cycle: 180
    min_shift_duration: 90
    new_users_start_as_beginner: true
    allow_extra_shifts: true
    max_time_in_advance_to_book_extra_shifts: "3 days"
    forbid_shift_overlap_time: 30
    fly_and_fixed_allow_fixed_shift_free: false
    maximum_nb_of_beneficiaries_in_membership: 2
    helloasso_registration_campaign_url: "https://www.helloasso.com/associations/my-local-coop/adhesions/re-adhesion"
    transactional_mailer_user: "contact@yourcoop.local"
    transactional_mailer_user_name: "espace membre"
    # icons
    user_account_not_enabled_material_icon: "person_outline"
    user_account_enabled_material_icon: "person"
    member_withdrawn_material_icon: "exit_to_app"
    member_withdrawn_background_color: "#f44336"
    member_frozen_material_icon: "ac_unit"
    member_frozen_background_color: "#2196f3"
    member_exempted_material_icon: "umbrella"
    member_exempted_background_color: "#9c27b0"
    member_registration_missing_material_icon: "warning"
    member_registration_missing_background_color: "#ff9800"
    beneficiary_main_icon: "star"
    beneficiary_new_icon: "new_releases"
    display_swipe_cards_settings: true
    display_freeze_account: true
    display_freeze_account_false_message: "Le gel n'est pas possible actuellement"
    display_keys_shop: true
    display_name_shifters: true
    use_card_reader_to_validate_shifts: true
    profile_display_task_list: true
    profile_display_time_log: true
    display_gauge: true
    max_nb_of_past_cycles_to_display: 3
    max_event_proxy_per_member: 1
    emails.contact:
        { from_name: "Contact Localcoop", address: "contact@yourcoop.local" }
    emails.member:
        { from_name: "Membres Localcoop", address: "membres@yourcoop.local" }
    emails.shift:
        { from_name: "Créneaux Localcoop", address: "creneaux@yourcoop.local" }
    emails.formation:
        {
            from_name: "Formation Localcoop",
            address: "formations@yourcoop.local",
        }
    emails.admin:
        { from_name: "Admin Localcoop", address: "admin@yourcoop.local" }
    emails.noreply:
        { from_name: "Ne pas répondre", address: "noreply@yourcoop.local" }
    emails.sendable:
        - "%emails.contact%"
        - "%emails.member%"
        - "%emails.shift%"
        - "%emails.formation%"
        - "%emails.admin%"
        - "%emails.noreply%"
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
